try {
    hello();
}
catch (error){
    console.log(error);
}

try{
    anotherFunction();
}
catch {
    console.log('This is an error');
}